grammar(semantics: &mut Semantics);
use crate::scanner::Token;
use crate::semantics::Semantics;
use crate::semantics::func_types::FuncType;
use crate::semantics::var_types::VarType;

extern {
    type Location = usize;
    type Error = ();
    
    enum Token {
        "programa" => Token::Programa,
        "inicio" => Token::Inicio,
        "fin" => Token::Fin,
        "entero" => Token::Entero,
        "flotante" => Token::Flotante,
        "vars" => Token::Variable,
        "escribe" => Token::Escribe,
        "nula" => Token::Nula,
        "mientras" => Token::Mientras,
        "haz" => Token::Haz,
        "si" => Token::Si,
        "sino" => Token::Sino,
        ";" => Token::PuntoYComa,
        ":" => Token::DosPuntos,
        "," => Token::Coma,
        "{" => Token::LlaveAbrir,
        "}" => Token::LlaveCerrar,
        "[" => Token::CorcheteAbrir,
        "]" => Token::CorcheteCerrar,
        "(" => Token::ParentesisAbrir,
        ")" => Token::ParentesisCerrar,
        "==" => Token::ComparadorIgual,
        "!=" => Token::NoIgual,
        ">" => Token::Mayor,
        "<" => Token::Menor,
        "=" => Token::Igual,
        "+" => Token::Mas,
        "-" => Token::Menos,
        "*" => Token::Multiplicar,
        "/" => Token::Dividir,
        
        Entero => Token::ConstanteEntero(<i64>),
        Flotante => Token::ConstanteFlotante(<f64>),
        Letrero => Token::Letrero(<String>),
        Identificador => Token::Identificador(<String>),
    }
}

// Punto neurálgico 6 (final)
pub Programa: () = {
    ProgramaSemantics ProgramaIdSemantics ";" OpcionesPrograma "inicio" Cuerpo "fin" => {
        let _ = semantics.dir_func.delete_all();
    }
};

// Punto neurálgico 1
pub ProgramaSemantics: () = {
    "programa" => {
        let _ = semantics.dir_func.create_dir_func();
    }
}

// Punto neurálgico 2
pub ProgramaIdSemantics: () = {
    <_id:Identificador> => {
        let _ = semantics.dir_func.add_func(_id.clone(), FuncType::Program);
        let _ = semantics.dir_func.add_func(format!("global-{}", _id.clone()).to_string(), FuncType::Nula);
    }
}

OpcionesPrograma: () = {
    Vars ListaFuncs => (),
    ListaFuncs => (),
};

ListaFuncs: () = {
    Funcs ListaFuncs => (),
    => (),
};

Vars: () = {
    VarsNewTable ListaVars => (),
};

// Punto neurálgico 3
VarsNewTable: () = {
    "vars" => {
        let _ = semantics.dir_func.create_var_table();
    }
};

ListaVars: () = {
    ListaId ":" Tipo ";" AgregarVars => (),
};

ListaId: () = {
    NewVar AgregarId => (),
};

// Punto neurálgico 4
NewVar: () = {
    <_id:Identificador> => {
        let _ = semantics.dir_func.add_var_name(_id.clone());
    }
};

AgregarId: () = {
    "," ListaId => (),
    => (),
};

AgregarVars: () = {
    ListaVars => (),
    => (),
};

Funcs: () = {
    AddFuncSemantics DefFunc => (),
};

AddFuncSemantics: () = {
    "nula" <_id:Identificador> => {
        let _ = semantics.dir_func.add_func(_id.clone(), FuncType::Nula);
    },
    "entero" <_id:Identificador> => {
        let _ = semantics.dir_func.add_func(_id.clone(), FuncType::Entero);
    },
    "flotante" <_id:Identificador> => {
        let _ = semantics.dir_func.add_func(_id.clone(), FuncType::Flotante);
    }
}

DefFunc: () = {
    "(" ListaArgs ")" "{" OpcionVars Cuerpo "}" ";" => (),
};

ListaArgs: () = {
    Args => (),
    => (),
};

Args: () = {
    ArgsVarSemantics AgregarArgs => (),
};

// Punto neurálgico 5
ArgsVarSemantics: () = {
    <_id:Identificador> ":" Tipo => {
        let _ = semantics.dir_func.add_var_name(_id.clone());
    }
};

AgregarArgs: () = {
    "," Args => (),
    => (),
};

OpcionVars: () = {
    Vars => (),
    => (),
};

Cuerpo: () = {
    "{" ListaEstatuto "}" => (),
};

ListaEstatuto: () = {
    Estatuto ListaEstatuto => (),
    => (),
};

Tipo: () = {
    "entero" => {
        let _ = semantics.dir_func.add_vars(VarType::Entero);
    },
    "flotante" => {
        let _ = semantics.dir_func.add_vars(VarType::Flotante);
    },
};

Estatuto: () = {
    <_id:Identificador> AsignaOLlamada => (),
    Condicion => (),
    Ciclo => (),
    Imprime => (),
    "[" ListaEstatutoAdentro "]" => (),
};

ListaEstatutoAdentro: () = {
    Estatuto ListaEstatutoAdentro => (),
    => (),
};

AsignaOLlamada: () = {
    "=" Expresion ";" => (),
    LlamadaSinId => (),
};

Condicion: () = {
    "si" "(" Expresion ")" Cuerpo OpcionSino ";" => (),
};

OpcionSino: () = {
    "sino" Cuerpo => (),
    => (),
};

Ciclo: () = {
    "mientras" "(" Expresion ")" "haz" Cuerpo ";" => (),
};

LlamadaSinId: () = {
    "(" ListaExpresion ")" ";" => (),
};

Llamada: () = {
    <_id:Identificador> LlamadaSinId => (),
};

ListaExpresion: () = {
    Expresion AgregarExpresion => (),
    => (),
};

AgregarExpresion: () = {
    "," Expresion AgregarExpresion => (),
    => (),
};

Imprime: () = {
    "escribe" "(" OpcionImprime ")" ";" => (),
};

OpcionImprime: () = {
    ElementoImprime AgregarOpcionImprime => (),
};

ElementoImprime: () = {
    Expresion => (),
    <_l:Letrero> => (),
};

AgregarOpcionImprime: () = {
    "," ElementoImprime AgregarOpcionImprime => (),
    => (),
};

Expresion: () = {
    Exp OpcionExp => (),
};

OpcionExp: () = {
    ">" Exp => (),
    "<" Exp => (),
    "!=" Exp => (),
    "==" Exp => (),
    => (),
};

Exp: () = {
    Termino AgregarTermino => (),
};

AgregarTermino: () = {
    "+" Exp => (),
    "-" Exp => (),
    => (),
};

Termino: () = {
    Factor AgregarFactor => (),
};

AgregarFactor: () = {
    "*" Termino => (),
    "/" Termino => (),
    => (),
};

Factor: () = {
    "(" Expresion ")" => (),
    Signo Valor => (),
    Constante => (),
    <_id:Identificador> OpcionFactorId=> (),
};

OpcionFactorId: () = {
    LlamadaSinId => (),
    => (),
};

Signo: () = {
    "-" => (),
    "+" => (),
};

Valor: () = {
    <_id:Identificador> => (),
    Constante => (),
};

Constante: () = {
    <_c:Entero> => (),
    <_c:Flotante> => (),
};
