grammar;
use crate::scanner::Token;

extern {
    type Location = usize;
    type Error = ();
    
    enum Token {
        "programa" => Token::Programa,
        "inicio" => Token::Inicio,
        "fin" => Token::Fin,
        "entero" => Token::Entero,
        "flotante" => Token::Flotante,
        "vars" => Token::Variable,
        "escribe" => Token::Escribe,
        "nula" => Token::Nula,
        "mientras" => Token::Mientras,
        "haz" => Token::Haz,
        "si" => Token::Si,
        "sino" => Token::Sino,
        ";" => Token::PuntoYComa,
        ":" => Token::DosPuntos,
        "," => Token::Coma,
        "{" => Token::LlaveAbrir,
        "}" => Token::LlaveCerrar,
        "[" => Token::CorcheteAbrir,
        "]" => Token::CorcheteCerrar,
        "(" => Token::ParentesisAbrir,
        ")" => Token::ParentesisCerrar,
        "==" => Token::ComparadorIgual,
        "!=" => Token::NoIgual,
        ">" => Token::Mayor,
        "<" => Token::Menor,
        "=" => Token::Igual,
        "+" => Token::Mas,
        "-" => Token::Menos,
        "*" => Token::Multiplicar,
        "/" => Token::Dividir,
        
        Entero => Token::ConstanteEntero(<i64>),
        Flotante => Token::ConstanteFlotante(<f64>),
        Letrero => Token::Letrero(<String>),
        Identificador => Token::Identificador(<String>),
    }
}

pub Programa: () = {
    "programa" <_id:Identificador> ";" OpcionesPrograma "inicio" Cuerpo "fin" => ()
};

OpcionesPrograma: () = {
    Vars ListaFuncs => (),
    ListaFuncs => (),
};

ListaFuncs: () = {
    Funcs ListaFuncs => (),
    => (),
};

Vars: () = {
    "vars" ListaVars => (),
};

ListaVars: () = {
    ListaId ":" Tipo ";" AgregarVars => (),
};

ListaId: () = {
    <_id:Identificador> AgregarId => (),
};

AgregarId: () = {
    "," ListaId => (),
    => (),
};

AgregarVars: () = {
    ListaVars => (),
    => (),
};

Funcs: () = {
    "nula" DefFunc => (),
    Tipo DefFunc => (),
};

DefFunc: () = {
    <_id:Identificador> "(" ListaArgs ")" "{" OpcionVars Cuerpo "}" ";" => (),
};

ListaArgs: () = {
    Args => (),
    => (),
};

Args: () = {
    <_id:Identificador> ":" Tipo AgregarArgs => (),
};

AgregarArgs: () = {
    "," Args => (),
    => (),
};

OpcionVars: () = {
    Vars => (),
    => (),
};

Cuerpo: () = {
    "{" ListaEstatuto "}" => (),
};

ListaEstatuto: () = {
    Estatuto ListaEstatuto => (),
    => (),
};

Tipo: () = {
    "entero" => (),
    "flotante" => (),
};

Estatuto: () = {
    <_id:Identificador> AsignaOLlamada => (),
    Condicion => (),
    Ciclo => (),
    Imprime => (),
    "[" ListaEstatutoAdentro "]" => (),
};

ListaEstatutoAdentro: () = {
    Estatuto ListaEstatutoAdentro => (),
    => (),
};

AsignaOLlamada: () = {
    "=" Expresion ";" => (),
    LlamadaSinId => (),
};

Condicion: () = {
    "si" "(" Expresion ")" Cuerpo OpcionSino ";" => (),
};

OpcionSino: () = {
    "sino" Cuerpo => (),
    => (),
};

Ciclo: () = {
    "mientras" "(" Expresion ")" "haz" Cuerpo ";" => (),
};

LlamadaSinId: () = {
    "(" ListaExpresion ")" ";" => (),
};

Llamada: () = {
    <_id:Identificador> LlamadaSinId => (),
};

ListaExpresion: () = {
    Expresion AgregarExpresion => (),
    => (),
};

AgregarExpresion: () = {
    "," Expresion AgregarExpresion => (),
    => (),
};

Imprime: () = {
    "escribe" "(" OpcionImprime ")" ";" => (),
};

OpcionImprime: () = {
    ElementoImprime AgregarOpcionImprime => (),
};

ElementoImprime: () = {
    Expresion => (),
    <_l:Letrero> => (),
};

AgregarOpcionImprime: () = {
    "," ElementoImprime AgregarOpcionImprime => (),
    => (),
};

Expresion: () = {
    Exp OpcionExp => (),
};

OpcionExp: () = {
    ">" Exp => (),
    "<" Exp => (),
    "!=" Exp => (),
    "==" Exp => (),
    => (),
};

Exp: () = {
    Termino AgregarTermino => (),
};

AgregarTermino: () = {
    "+" Exp => (),
    "-" Exp => (),
    => (),
};

Termino: () = {
    Factor AgregarFactor => (),
};

AgregarFactor: () = {
    "*" Termino => (),
    "/" Termino => (),
    => (),
};

Factor: () = {
    "(" Expresion ")" => (),
    Signo Valor => (),
    Constante => (),
    <_id:Identificador> OpcionFactorId=> (),
};

OpcionFactorId: () = {
    LlamadaSinId => (),
    => (),
};

Signo: () = {
    "-" => (),
    "+" => (),
};

Valor: () = {
    <_id:Identificador> => (),
    Constante => (),
};

Constante: () = {
    <_c:Entero> => (),
    <_c:Flotante> => (),
};
