grammar(semantics: &mut Semantics, quad_generator: &mut QuadGenerator);
use crate::scanner::Token;
use crate::semantics::Semantics;
use crate::quads::QuadGenerator;
use crate::semantics::func_types::FuncType;
use crate::semantics::var_types::VarType;
use crate::quads::operator_group::OperatorGroup;
use crate::quads::quad_operators::QuadOperator;
use crate::quads::quad_value::QuadValue;
use crate::memory::MemoryManager;
use crate::semantics::semantic_error::SemanticError;

extern {
    type Location = usize;
    type Error = ();
    
    enum Token {
        "programa" => Token::Programa,
        "inicio" => Token::Inicio,
        "fin" => Token::Fin,
        "entero" => Token::Entero,
        "flotante" => Token::Flotante,
        "vars" => Token::Variable,
        "escribe" => Token::Escribe,
        "nula" => Token::Nula,
        "mientras" => Token::Mientras,
        "haz" => Token::Haz,
        "si" => Token::Si,
        "sino" => Token::Sino,
        ";" => Token::PuntoYComa,
        ":" => Token::DosPuntos,
        "," => Token::Coma,
        "{" => Token::LlaveAbrir,
        "}" => Token::LlaveCerrar,
        "[" => Token::CorcheteAbrir,
        "]" => Token::CorcheteCerrar,
        "(" => Token::ParentesisAbrir,
        ")" => Token::ParentesisCerrar,
        "==" => Token::ComparadorIgual,
        "!=" => Token::NoIgual,
        ">" => Token::Mayor,
        "<" => Token::Menor,
        "=" => Token::Igual,
        "+" => Token::Mas,
        "-" => Token::Menos,
        "*" => Token::Multiplicar,
        "/" => Token::Dividir,
        "retorna" => Token::Retorna,
        
        Entero => Token::ConstanteEntero(<i64>),
        Flotante => Token::ConstanteFlotante(<f64>),
        Letrero => Token::Letrero(<String>),
        Identificador => Token::Identificador(<String>),
    }
}

// Punto neurálgico 6 (final)
pub Programa: () = {
    ProgramaSemantics ProgramaIdSemantics ";" OpcionesPrograma Inicio Cuerpo "fin" => {
        quad_generator.push_end();
    }
};

// Punto neurálgico 1
pub ProgramaSemantics: () = {
    "programa" => {
        quad_generator.push_start();
        semantics.dir_func.create_dir_func();
    }
}

// Punto neurálgico 2
pub ProgramaIdSemantics: () = {
    <_id:Identificador> => {
        if let Err(e) = semantics.dir_func.add_func(_id.clone(), FuncType::Program, 0) { semantics.push_error(e); }
        if let Err(e) = semantics.dir_func.add_func(format!("global-{}", _id.clone()).to_string(), FuncType::Nula, 0) { semantics.push_error(e); }
    }
}

// Punto neurálgico Quads - Inicio
pub Inicio: () = {
    "inicio" => {
        quad_generator.push_main();
    }
}

OpcionesPrograma: () = {
    Vars ListaFuncs => (),
    ListaFuncs => (),
};

ListaFuncs: () = {
    Funcs ListaFuncs => (),
    => (),
};

Vars: () = {
    VarsNewTable ListaVars => (),
};

// Punto neurálgico 3
VarsNewTable: () = {
    "vars" => {
        if let Err(e) = semantics.dir_func.create_var_table() { semantics.push_error(e); }
    }
};

// Punto neurálgico Func 5
ListaVars: () = {
    ListaId ":" Tipo ";" AgregarVars => {
        if let Err(e) = semantics.dir_func.save_local_count() { semantics.push_error(e); }
    },
};

ListaId: () = {
    NewVar AgregarId => (),
};

// Punto neurálgico 4
NewVar: () = {
    <_id:Identificador> => {
        semantics.dir_func.add_var_name(_id.clone());
    }
};

AgregarId: () = {
    "," ListaId => (),
    => (),
};

AgregarVars: () = {
    ListaVars => (),
    => (),
};

Funcs: () = {
    AddFuncSemantics DefFunc => (),
};

// Punto neurálgico Func 1
AddFuncSemantics: () = {
    "nula" <_id:Identificador> => {
        if let Err(e) = semantics.dir_func.add_func(_id.clone(), FuncType::Nula, quad_generator.get_counter()) { semantics.push_error(e); }
    },
    "entero" <_id:Identificador> => {
        if let Err(e) = semantics.dir_func.add_func(_id.clone(), FuncType::Entero, quad_generator.get_counter()) { semantics.push_error(e); }
    },
    "flotante" <_id:Identificador> => {
        if let Err(e) = semantics.dir_func.add_func(_id.clone(), FuncType::Flotante, quad_generator.get_counter()) { semantics.push_error(e); }
    }
}

// Punto neurálgico Func 6
DefFunc: () = {
    "(" FuncArgStart ListaArgs ParamCount "{" OpcionVars Cuerpo "}" ";" => {
        if let Err(e) = semantics.dir_func.release_var_table() { semantics.push_error(e); }
        quad_generator.push_func_end();
        let temp_count = quad_generator.get_temp_count();
        if let Err(e) = semantics.dir_func.add_temp_count(temp_count) { semantics.push_error(e); }
        MemoryManager::with_instance(|memory_manager| memory_manager.reset_function_scope());
    },
};

// Punto neurálgico Func 2
pub FuncArgStart: () = {
    => {
        if let Err(e) = semantics.dir_func.create_var_table() { semantics.push_error(e); }
    }
};

// Punto neurálgico Func 4
pub ParamCount: () = {
    ")" => {
        if let Err(e) = semantics.dir_func.save_param_count() { semantics.push_error(e); }
    }
};

ListaArgs: () = {
    Args => (),
    => (),
};

Args: () = {
    ArgsVarSemantics AgregarArgs => (),
};

// Punto neurálgico Func 3
ArgsVarSemantics: () = {
    <_id:Identificador> ":" "entero" => {
        semantics.dir_func.add_var_name(_id.clone());
        if let Err(e) = semantics.dir_func.add_vars(VarType::Entero) { semantics.push_error(e); }
        if let Err(e) = semantics.dir_func.add_param(VarType::Entero) { semantics.push_error(e); }
    },
    <_id:Identificador> ":" "flotante" => {
        semantics.dir_func.add_var_name(_id.clone());
        if let Err(e) = semantics.dir_func.add_vars(VarType::Flotante) { semantics.push_error(e); }
        if let Err(e) = semantics.dir_func.add_param(VarType::Flotante) { semantics.push_error(e); }
    }
};

AgregarArgs: () = {
    "," Args => (),
    => (),
};

OpcionVars: () = {
    Vars => (),
    => (),
};

Cuerpo: () = {
    "{" ListaEstatuto Return"}" => (),
};

Return: () = {
    "retorna" Expresion ";" => {
        if let Some(ret_type) = quad_generator.peek_top_type() {
            if let Err(e) = semantics.dir_func.check_return_type(ret_type) {
                semantics.push_error(e);
            }
        }
        match semantics.dir_func.get_curr_address() {
            Ok(addr) => quad_generator.push_return(addr),
            Err(e) => semantics.push_error(e),
        }
    },
    => (),
}

ListaEstatuto: () = {
    Estatuto ListaEstatuto => (),
    => (),
};

// Punto neurálgico 5
Tipo: () = {
    "entero" => {
        if let Err(e) = semantics.dir_func.add_vars(VarType::Entero) { semantics.push_error(e); }
    },
    "flotante" => {
        if let Err(e) = semantics.dir_func.add_vars(VarType::Flotante) { semantics.push_error(e); }
    },
};

Estatuto: () = {
    Imprime => (),
    AsignaOLlamada => (),
    Condicion => (),
    Ciclo => (),
    "[" ListaEstatutoAdentro "]" => (),
};

ListaEstatutoAdentro: () = {
    Estatuto ListaEstatutoAdentro => (),
    => (),
};

AsignaOLlamada: () = {
    // Punto neurálgico Quads 8
    <_id:Identificador> "=" Expresion ";" => {
        match semantics.dir_func.get_var_info(&_id) {
            Ok((address, var_type)) => quad_generator.push_id(address, var_type),
            Err(e) => semantics.push_error(e),
        }
        quad_generator.equals_quad();
    },

    CheckFuncId LlamadaSinId => (),
};

// Punto neurálgico Func Call 1
pub CheckFuncId: () = {
    <_id:Identificador> => {
        if let Err(e) = semantics.dir_func.check_func_id(&_id.clone()) { semantics.push_error(e); }
        quad_generator.push_func_era(_id.clone());
    }
};

Condicion: () = {
    "si" "(" Expresion IfStart Cuerpo OpcionSino IfEnd => (),
};

// Punto neurálgico If 1
pub IfStart: () = {
    ")" => {
        quad_generator.push_if_start();
    }
};

// Punto neurálgico If 2
pub IfEnd: () = {
    ";" => {
        quad_generator.push_if_end();
    }
};

OpcionSino: () = {
    Else Cuerpo => (),
    => (),
};

// Punto neurálgico If 3
pub Else: () = {
    "sino" => {
        quad_generator.push_else();
    }
};

Ciclo: () = {
    WhileStart "(" Expresion ")" WhileExpression Cuerpo WhileEnd => (),
};

// Punto neurálgico While 1
pub WhileStart: () = {
    "mientras"=> {
        quad_generator.push_while_start();
    }
};

// Punto neurálgico While 2
pub WhileExpression: () = {
    "haz" => {
        quad_generator.push_while_expression();
    }
};

// Punto neurálgico While 3
pub WhileEnd: () = {
    ";" => {
        quad_generator.push_while_end();
    }
};

LlamadaSinId: () = {
    "(" ListaExpresion ")" ";" => {
        let parameter_counter = quad_generator.get_arg_count();
        if let Err(e) = semantics.dir_func.check_func_param_count(parameter_counter) { semantics.push_error(e); }
        if let Ok(func_name) = semantics.dir_func.get_func_name() {
            let return_info = semantics.dir_func.get_call_func_return_info();
            quad_generator.push_func_gosub(func_name, return_info);
        }
    },
};

ListaExpresion: () = {
    ArgCheck AgregarExpresion => (),
    => (),
};

// Punto neurálgico Func Call 2
pub ArgCheck: () = {
    Expresion => {
        let (var_type, param_num) = quad_generator.push_func_arg();
        if let Err(e) = semantics.dir_func.check_func_arg(var_type, param_num) { semantics.push_error(e); }
    }
};

AgregarExpresion: () = {
    MoveParamCounter ArgCheck AgregarExpresion => (),
    => (),
};

// Punto neurálgico Func Call 3
pub MoveParamCounter: () = {
    "," => {
        quad_generator.parameter_counter_next();
    }
};

Imprime: () = {
    "escribe" "(" OpcionImprime ")" ";" => (),
};

OpcionImprime: () = {
    ElementoImprime AgregarOpcionImprime => (),
};

ElementoImprime: () = {
    Expresion => {
        quad_generator.push_print();
    },
    <_l:Letrero> => {
        quad_generator.push_string(_l.clone());
        quad_generator.push_print();
    },
};

AgregarOpcionImprime: () = {
    "," ElementoImprime AgregarOpcionImprime => (),
    => (),
};

Expresion: () = {
    Exp OpcionExp => (),
};

OpcionExp: () = {
    PushMayor Exp ChecarRel => (),
    PushMenor Exp ChecarRel => (),
    PushNoIgual Exp ChecarRel => (),
    PushIgual Exp ChecarRel => (),
    => (),
};

Exp: () = {
    Termino AgregarTermino => (),
};

// Punto neurálgico Quads 4
pub ChecarSumSub: () = {
    => {
        if let Some(err) = quad_generator.check_operator(OperatorGroup::SumSub) {
            semantics.push_error(SemanticError { message: err });
        }
    }
};

AgregarTermino: () = {
    PushMas Termino ChecarSumSub AgregarTermino => (),
    PushMenos Termino ChecarSumSub AgregarTermino => (),
    => (),
};

// Punto neurálgico Quads 3
pub PushMas: () = {
    "+" => {
        quad_generator.push_operator(QuadOperator::Mas);
    }
}

// Punto neurálgico Quads 3
pub PushMenos: () = {
    "-" => {
        quad_generator.push_operator(QuadOperator::Menos);
    }
}

Termino: () = {
    Factor AgregarFactor => (),
};

// Punto neurálgico Quads 6
pub ChecarMultDiv: () = {
    => {
        if let Some(err) = quad_generator.check_operator(OperatorGroup::MultDiv) {
            semantics.push_error(SemanticError { message: err });
        }
    }
};

AgregarFactor: () = {
    PushMult Factor ChecarMultDiv AgregarFactor => (),
    PushDiv Factor ChecarMultDiv AgregarFactor => (),
    => (),
};

// Punto neurálgico Quads 5
pub PushMult: () = {
    "*" => {
        quad_generator.push_operator(QuadOperator::Multiplicar);
    }
}

// Punto neurálgico Quads 5
pub PushDiv: () = {
    "/" => {
        quad_generator.push_operator(QuadOperator::Dividir);
    }
}

// Punto neurálgico Quads 7
pub ChecarRel: () = {
    => {
        if let Some(err) = quad_generator.check_operator(OperatorGroup::Rel) {
            semantics.push_error(SemanticError { message: err });
        }
    }
};

// Punto neurálgico Quads 7
pub PushMayor: () = {
    ">" => {
        quad_generator.push_operator(QuadOperator::Mayor);
    }
}


// Punto neurálgico Quads 7
pub PushMenor: () = {
    "<" => {
        quad_generator.push_operator(QuadOperator::Menor);
    }
}


// Punto neurálgico Quads 7
pub PushNoIgual: () = {
    "!=" => {
        quad_generator.push_operator(QuadOperator::NoIgual);
    }
}


// Punto neurálgico Quads 7
pub PushIgual: () = {
    "==" => {
        quad_generator.push_operator(QuadOperator::ComparadorIgual);
    }
}

Factor: () = {
    "(" Expresion ")" => (),
    "+" <_c:Constante> => { quad_generator.push_constante(_c); },
    "-" <_c:Constante> => {
        let negated = match _c {
            QuadValue::Entero(v) => QuadValue::Entero(-v),
            QuadValue::Flotante(v) => QuadValue::Flotante(-v),
            QuadValue::Boleano(v) => QuadValue::Boleano(v),
        };
        quad_generator.push_constante(negated);
    },
    "+" <_id:Identificador> => {
        match semantics.dir_func.get_var_info(&_id) {
            Ok((address, var_type)) => quad_generator.push_id(address, var_type),
            Err(e) => semantics.push_error(e),
        }
    },
    "-" <_id:Identificador> => {
        match semantics.dir_func.get_var_info(&_id) {
            Ok((address, var_type)) => quad_generator.push_id(address, var_type),
            Err(e) => semantics.push_error(e),
        }
    },
    // Punto neurálgico Quads 2
    <_c:Constante> => { quad_generator.push_constante(_c); },
    
    CheckFuncId "(" ListaExpresion ")" => {
        let parameter_counter = quad_generator.get_arg_count();
        if let Err(e) = semantics.dir_func.check_func_param_count(parameter_counter) { semantics.push_error(e); }
        if let Ok(func_name) = semantics.dir_func.get_func_name() {
            let return_info = semantics.dir_func.get_call_func_return_info();
            quad_generator.push_func_gosub(func_name, return_info);
        }
    },
    PushId => (),
};

// Punto neurálgico Quads 1
pub PushId: () = {
    <_id:Identificador> => {
        match semantics.dir_func.get_var_info(&_id) {
            Ok((address, var_type)) => quad_generator.push_id(address, var_type),
            Err(e) => semantics.push_error(e),
        }
    }
};

Constante: QuadValue = {
    <_c:Entero> => { 
        QuadValue::Entero(_c) 
    },
    <_c:Flotante> => { 
        QuadValue::Flotante(_c) 
    },
};
