from enum import Enum

class QuadCode(Enum):
    ADD = '+'
    SUB = '-'
    MUL = '*'
    DIV = '/'
    ASSIGN = '='
    LT = '<'
    GT = '>'
    EQ = '=='
    NEQ = '!='
    PRINT = 'print'
    GOTO = 'goto'
    GOTOF = 'gotof'
    GOTOT = 'gotot'
    ERA = 'era'
    PARAM = 'param'
    GOSUB = 'gosub'
    RETURN = 'return'
    ENDFUNC = 'endfunc'
    END = 'end'